services:
  zookeeper:
    image: bitnami/zookeeper:latest
    ports: ["2181:2181"]

  kafka:
    image: bitnami/kafka:latest
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    ports: ["9092:9092"]

  spark-master:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=master
    ports: ["7077:7077"]

  spark-worker:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077

  flink-jobmanager:
    image: flink:latest
    command: jobmanager
    ports: ["8081:8081"]

  flink-taskmanager:
    image: flink:latest
    command: taskmanager
    depends_on:
      - flink-jobmanager
