version: 2

models:
  - name: stg_loan_stats
    description: "Accepted Lending Club loans (static snapshot to 2018)"
    columns:
      - name: loan_id
        description: "Unique loan identifier"

      - name: loan_amount
        description: "Original principal amount (USD)"
        tests:
          - not_null

      - name: term_months
        description: "Loan term in months"
        tests:
          - not_null

      - name: interest_rate
        description: "Annual interest rate (decimal)"
        tests:
          - not_null

      - name: issue_date
        description: "Date the loan was issued"
        tests:
          - not_null

  - name: stg_bank_prices
    description: "Daily OHLC & Volume for each bank ticker"
    columns:
      - name: ticker
        description: "Stock ticker symbol"
        tests:
          - not_null

      - name: date
        description: "Trade date"
        tests:
          - not_null

      - name: open_price
        description: "Opening price"
        tests:
          - not_null

      - name: high_price
        description: "High price"
        tests:
          - not_null

      - name: low_price
        description: "Low price"
        tests:
          - not_null

      - name: close_price
        description: "Closing price"
        tests:
          - not_null

      - name: volume
        description: "Trading volume"
        tests:
          - not_null

  - name: stg_macro
    description: "Monthly macro indicators from FRED"
    columns:
      - name: obs_date
        description: "Observation date"
        tests:
          - not_null
          - unique

      - name: unemployment_rate
        description: "Unemployment rate (%)"
        tests:
          - not_null

      - name: gdp_level
        description: "GDP level (billions USD)"
        tests:
          - not_null

      - name: cpi_level
        description: "CPI (base 1982–84 = 100)"
        tests:
          - not_null
